# remap prefix from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind-key c new-window -c "#{pane_current_path}"

# split panes using | and - 
bind-key | split-window -h
bind-key - split-window -v
unbind '"'
unbind %

# reload config file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# switch panes using Alt-hjkl without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R 

# Enable mouse control 
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# use vi-style keybindings in copy mode
setw -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"

# reduce escape delay to avoid tmux intercepting ESC
set -sg escape-time 10

# bind 'u' to enter copy mode and search backward for the prompt arrow
bind-key u copy-mode \; send-keys -X search-backward "➜"

